---
- hosts: all
  become: true
  become_user: root
  become_method: sudo
  vars_files:
    - "environments/{{ env }}/group_vars/main.yaml"
  roles:
    - base

- hosts: etcd
  become: true
  become_user: root
  become_method: sudo
  vars_files:
    - "environments/{{ env }}/group_vars/main.yaml"
    - "environments/{{ env }}/hosts_vars/main.yaml"
  roles:
    - etcd

- hosts: k8s
  become: true
  become_user: root
  become_method: sudo
  vars_files:
    - "environments/{{ env }}/group_vars/main.yaml"
    - "environments/{{ env }}/hosts_vars/main.yaml"
  roles:
    - flannel
    - docker
    - kubernetes-master
    - skydns

- hosts: node
  become: true
  become_user: root
  become_method: sudo
  vars_files:
    - "environments/{{ env }}/group_vars/main.yaml"
    - "environments/{{ env }}/hosts_vars/main.yaml"
  roles:
    - flannel
    - docker
    - kubernetes-node
