---
- hosts: all
  vars_files:
    - "environments/{{ env }}/group_vars/main.yaml"
  roles:
    - base

- hosts: etcd
  vars_files:
    - "environments/{{ env }}/group_vars/main.yaml"
    - "environments/{{ env }}/hosts_vars/main.yaml"
  roles:
    - etcd

- hosts: k8s
  vars_files:
    - "environments/{{ env }}/group_vars/main.yaml"
    - "environments/{{ env }}/hosts_vars/main.yaml"
  roles:
    - flannel
    - docker
    - kubernetes-master

- hosts: node
  vars_files:
    - "environments/{{ env }}/group_vars/main.yaml"
    - "environments/{{ env }}/hosts_vars/main.yaml"
  roles:
    - flannel
    - docker
    - kubernetes-node
