---
- name: start docker
  service: name=docker enabled=yes state=started

- name: restart docker
  service: name=docker state=restarted

- name: reload docker
  service: name=docker state=reloaded

- name: stop docker
  service: name=docker state=stopped
